export default {
  skipQuestions: ['body', 'breaking', 'footerPrefix', 'footer'],
  maxHeaderLength: 100,
  messages: {
    type: '选择本次提交类型:',
    scope: '选择影响范围（可选）:',
    customScope: '请输入影响范围:',
    subject: '简要说明（必填）:',
    body: '详细说明（可选）:',
    breaking: '非兼容变更（可选）:',
    footerPrefix: '关联 issue 前缀（可选）:',
    footer: '关联 issue（可选）:',
    confirmCommit: '确认提交?',
  },
  types: [
    { value: 'feat', name: 'feat:     新功能' },
    { value: 'fix', name: 'fix:      修复缺陷' },
    { value: 'docs', name: 'docs:     文档变更' },
    { value: 'style', name: 'style:    代码格式（不影响功能）' },
    { value: 'refactor', name: 'refactor: 重构（既不是新增也不是修复）' },
    { value: 'perf', name: 'perf:     性能优化' },
    { value: 'test', name: 'test:     测试相关' },
    { value: 'build', name: 'build:    构建/依赖相关' },
    { value: 'ci', name: 'ci:       CI 配置' },
    { value: 'chore', name: 'chore:    其他杂项' },
    { value: 'revert', name: 'revert:   回滚' },
  ],
}
